language: cpp

matrix:
  include:
    # linux + clang
    - os: linux
      dist: focal # clang 7.0.0, cmake 3.16.8, gcc 9.3.0
      addons:
        apt:
          sources: ppa:chris-lea/redis-server
          # packages:
          #   - clang-8
          #   - cmake
      env: MATRIX_EVAL="CC=clang && CXX=clang++"

    # linux + gcc
    - os: linux
      dist: focal # clang 7.0.0, cmake 3.16.8, gcc 9.3.0
      addons:
        apt:
          sources: ppa:chris-lea/redis-server
          packages:
            - freeglut3-dev
            - mesa-utils
      env: MATRIX_EVAL="CC=gcc && CXX=g++"

    # osx + gcc
    - os: osx
      osx_image: xcode12.2 # macOS 10.15.7
      env: MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" # prepend "brew install gcc@10" if it's not yet installed.

    # osx + clang
    - os: osx
      osx_image: xcode12.2 # macOS 10.15.7
      env: MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - ./scripts/install_catch2.sh ${TRAVIS_OS_NAME}
  # - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
  #       ./scripts/install_openGL.sh
  #   fi

script:
  - cmake -S. -Bbuild
  - cmake --build build
  - cd build && ctest
