language: cpp

matrix:
  include:
    # linux + clang
    - os: linux
      addons:
        apt:
          sources: *all_sources
          packages:
            - clang-8
            - cmake
      env: MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

    # linux + gcc
    - os: linux
      addons:
        apt:
          sources: *all_sources
          packages:
            - gcc-10
            - cmake
      env: MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

    # osx + gcc
    - os: osx
      osx_image: xcode12.2 # macOS 10.15.7
      env: MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" # prepend "brew install gcc@10" if it's not yet installed.

    # osx + clang
    - os: osx
      osx_image: xcode12.2 # macOS 10.15.7
      env: MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - ./scripts/install_catch2.sh ${TRAVIS_OS_NAME}

script:
  - cmake -S. -Bbuild
  - cmake --build build
  - cd build && ctest
