language: cpp
# compiler: # matrix expansion
#   - clang
#   - gcc # gcc is alias for clang on macOS.  

matrix:
  include:
    # linux + clang
    - os: linux
      addons:
        apt:
          sources: *all_sources
          packages:
            - clang-9
            - cmake
      env: MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

    # linux + gcc
    - os: linux
      addons:
        apt:
          sources: *all_sources
          packages:
            - g++-10
            - cmake
      env: MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

    # osx + gcc
    - os: osx
      osx_image: xcode12.2 # macOS 10.15.7
      env: MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" # prepend "brew install gcc@10" if it's not yet installed.

    # osx + clang
    - os: osx
      osx_image: xcode12.2 # macOS 10.15.7
      env: MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"
    - ./install_catch2.sh

script:
  - cmake -S. -Bbuild
  - cmake --build build
  - cd build && ctest
